npc_types['bear'] = {
			name="Bear",
			color={108,40,90},
			hostile=true,
			move='attack',
			tail=true,
			vocal=true,
			sounds={
				attack=love.audio.newSource({
								"npcs/bearbear-growl-1.mp3",
								"npcs/bearbear-growl-2.mp3",
								"npcs/bearbear-growl-3.mp3",
								"npcs/bearbear-growl-4.mp3",
								"npcs/bearbear-growl-5.mp3",
								"npcs/bearbear-growl-6.mp3",
								"npcs/bearbear-growl-7.mp3"
							     }),
				target=love.audio.newSource({
								"npcs/bearbear-growl-1.mp3",
								"npcs/bearbear-growl-2.mp3",
								"npcs/bearbear-growl-3.mp3",
								"npcs/bearbear-growl-4.mp3",
								"npcs/bearbear-growl-5.mp3",
								"npcs/bearbear-growl-6.mp3",
								"npcs/bearbear-growl-7.mp3"
							     }),
				distance=love.audio.newSource({
								"npcs/bearbear-noise-1.mp3",
								"npcs/bearbear-noise-2.mp3",
								"npcs/bearbear-noise-3.mp3",
								"npcs/bearbear-noise-4.mp3",
								"npcs/bearbear-noise-5.mp3",
								"npcs/bearbear-noise-6.mp3",
								"npcs/bearbear-noise-7.mp3",
								"npcs/bearbear-noise-8.mp3",
								"npcs/bearbear-noise-9.mp3"
							     }),
				die=love.audio.newSource({
								"npcs/bear/bear-death-1.mp3",
								"npcs/bear/bear-death-2.mp3",
								"npcs/bear/bear-death-3.mp3",
								"npcs/bear/bear-death-4.mp3",
								"npcs/bear/bear-death-5.mp3"
				})
			}
		}
