npc_types['chicken'] = {
			name="Chicken",
			color={148,198,180},
			hostile=false,
			move='random',
			vocal=true,
			max_health=3,
                        armour={
                                        {
                                                type="flesh",
                                                natural=true,
                                                value=1
                                        }
                        },
                        weapons={
                                        {
                                                name='beak',
                                                natural=true,
                                                attacks={
                                                        {
                                                                verbs={'pecks','pokes','scrapes','nips'},
                                                                damage={dice_qty=1,dice_sides=1,plus=0},
                                                                critical_chance_multiplier=0.2
                                                        }
                                                }
                                        }
                        },
			sounds={
				attack=love.audio.newSource({
					"npcs/chicken/chicken-1.mp3",
					"npcs/chicken/chicken-2.mp3",
					"npcs/chicken/chicken-3.mp3",
					"npcs/chicken/chicken-4.mp3",
					"npcs/chicken/chicken-5.mp3",
					"npcs/chicken/chicken-6.mp3",
					"npcs/chicken/chicken-7.mp3"
							     })
			}
		}
