npc_types['dog'] = {
			name="Dog",
			color={198,40,90},
			hostile=true,
			move='attack',
			tail=true,
			vocal=true,
			max_health=10,
			armour={
                			{
                        			type="flesh",
                        			natural=true,                   -- means cannot be lost/destroyed
                        			value=1                         -- defensively almost useless
                			}
            		},
     			weapons={
                			{
                        			name='teeth',
                        			natural=true,                   -- means cannot be disarmed
                        			attacks={
                                			{
                                        			verbs={'bites','gnaws','seizes','chomps on','takes a chunk out of','sinks in to'},
                                        			damage={dice_qty=1,dice_sides=2,plus=0},
                                        			critical_chance_multiplier=2
                                			}
                               			}
                			}
             		},
			images={
				"npcs/dog/1.svg.gz",
				"npcs/dog/2.svg.gz",
				"npcs/dog/3.svg.gz",
				"npcs/dog/4.svg.gz",
				"npcs/dog/5.svg.gz",
				"npcs/dog/6.svg.gz",
				"npcs/dog/7.svg.gz",
				"npcs/dog/8.svg.gz",
				"npcs/dog/9.svg.gz",
				"npcs/dog/10.svg.gz"
			},
			sounds={
				attack=love.audio.newSource({
									"npcs/dog/dog-bark-1.mp3",
									"npcs/dog/dog-bark-10.mp3",
									"npcs/dog/dog-bark-11.mp3",
									"npcs/dog/dog-bark-12.mp3",
									"npcs/dog/dog-bark-13.mp3",
									"npcs/dog/dog-bark-14.mp3",
									"npcs/dog/dog-bark-15.mp3",
									"npcs/dog/dog-bark-16.mp3",
									"npcs/dog/dog-bark-17.mp3",
									"npcs/dog/dog-bark-18.mp3",
									"npcs/dog/dog-bark-19.mp3",
									"npcs/dog/dog-bark-2.mp3",
									"npcs/dog/dog-bark-20.mp3",
									"npcs/dog/dog-bark-21.mp3",
									"npcs/dog/dog-bark-22.mp3",
									"npcs/dog/dog-bark-23.mp3",
									"npcs/dog/dog-bark-24.mp3",
									"npcs/dog/dog-bark-3.mp3",
									"npcs/dog/dog-bark-4.mp3",
									"npcs/dog/dog-bark-5.mp3",
									"npcs/dog/dog-bark-6.mp3",
									"npcs/dog/dog-bark-7.mp3",
									"npcs/dog/dog-bark-8.mp3",
									"npcs/dog/dog-bark-9.mp3",
									"npcs/dog/dog-small-bark-1.mp3"
							     }),
				target=love.audio.newSource({
												"npcs/dog/dog-growl-1.mp3",
												"npcs/dog/dog-growl-2.mp3",
												"npcs/dog/dog-growl-3.mp3",
												"npcs/dog/dog-growl-4.mp3",
												"npcs/dog/dog-grunt-1.mp3",
												"npcs/dog/dog-snarl-1.mp3"
							     }),
				distance=love.audio.newSource({
												"npcs/dog/dog-howl-1.mp3",
												"npcs/dog/dog-howl-2.mp3",
												"npcs/dog/dog-howl-3.mp3"
							     }),
				die=love.audio.newSource({
												"npcs/dog/dog-whine-1.mp3",
												"npcs/dog/dog-whine-10.mp3",
												"npcs/dog/dog-whine-11.mp3",
												"npcs/dog/dog-whine-12.mp3",
												"npcs/dog/dog-whine-2.mp3",
												"npcs/dog/dog-whine-3.mp3",
												"npcs/dog/dog-whine-4.mp3",
												"npcs/dog/dog-whine-5.mp3",
												"npcs/dog/dog-whine-6.mp3",
												"npcs/dog/dog-whine-7.mp3",
												"npcs/dog/dog-whine-8.mp3",
												"npcs/dog/dog-whine-9.mp3"
				})
			}
		}
