npc_types['goblin'] = {
			name="Goblin",
			color={30,138,30},
			hostile=true,
			move='attack',
			vocal=true,
			max_health=11,
                        armour={
                                        {
                                                type="flesh",
                                                natural=true,                   -- means cannot be lost/destroyed
                                                value=2                         -- defensively quite ok
                                        }
                        },
			images={
				"npcs/goblin/1.svg.gz",
				"npcs/goblin/2.svg.gz",
				"npcs/goblin/3.svg.gz",
				"npcs/goblin/4.svg.gz",
				"npcs/goblin/5.svg.gz",
				"npcs/goblin/6.svg.gz",
				"npcs/goblin/7.svg.gz",
				"npcs/goblin/8.svg.gz",
				"npcs/goblin/9.svg.gz"
			},
                        weapons={
                                        {
                                                name='sword',
                                                natural=false,
                                                likelihood=5,
                                                attacks={
                                                        {
								likelihood=4,
                                                                verbs={'swings','slashes','slices','cleaves','scrapes','lacerates','chops','rends','carves','hacks','incises','cuts'},
                                                                damage={dice_qty=1,dice_sides=6,plus=0},
                                                                critical_chance_multiplier=1.8
                                                        },
                                                        {
								likelihood=6,
                                                                verbs={'pokes','skewers','pierces','lances','stabs','perforates','pricks','spears','sticks'},
                                                                damage={dice_qty=1,dice_sides=4,plus=0},
                                                                critical_chance_multiplier=0.8
                                                        }
                                                }
                                        },
                                        {
                                                name='body',
                                                natural=true,
                                                likelihood=1,
                                                attacks={
                                                        {
                                                                verbs={'bashes','knocks','charges','runs in to','smashes'},
                                                                damage={dice_qty=1,dice_sides=4,plus=1},
                                                                critical_chance_multiplier=0.3
                                                        }
                                                }
                                        },
                                        {
                                                name='foot',
                                                natural=true,
                                                likelihood=2,
                                                attacks={
                                                        {
                                                                verbs={'kicks','roundhouses','punts','side kicks','crescent kicks','reverse roundhouses'},
                                                                damage={dice_qty=1,dice_sides=4,plus=0},
                                                                critical_chance_multiplier=0.3
                                                        }
                                                }
                                        },
                                        {
                                                name='fist',
                                                natural=true,
                                                likelihood=2,
                                                attacks={
                                                        {
                                                                verbs={'punches','whacks','smashes','hits','clocks'},
                                                                damage={dice_qty=1,dice_sides=4,plus=0},
                                                                critical_chance_multiplier=0.3
                                                        }
                                                }
                                        }
                        },
			sounds={
				attack=love.audio.newSource({
					"sounds/impact/punch-1.mp3",
					"sounds/impact/punch-2.mp3",
					"sounds/impact/punch-3.mp3",
					"sounds/impact/punch-4.mp3",
					"sounds/impact/punch-5.mp3",
					"sounds/impact/punch-6.mp3",
					"sounds/impact/punch-7.mp3",
					"sounds/impact/punch-8.mp3",
					"sounds/impact/punch-9.mp3",
					"sounds/impact/punch-10.mp3",
				}),
				distance=love.audio.newSource({
					"npcs/goblin/goblin-1.mp3",
					"npcs/goblin/goblin-2.mp3",
					"npcs/goblin/goblin-3.mp3",
					"npcs/goblin/goblin-4.mp3",
					"npcs/goblin/goblin-5.mp3",
					"npcs/goblin/goblin-6.mp3",
					"npcs/goblin/goblin-7.mp3"
				}),
				target=love.audio.newSource({
					"npcs/goblin/goblin-1.mp3",
					"npcs/goblin/goblin-2.mp3",
					"npcs/goblin/goblin-3.mp3",
					"npcs/goblin/goblin-4.mp3",
					"npcs/goblin/goblin-5.mp3",
					"npcs/goblin/goblin-6.mp3",
					"npcs/goblin/goblin-7.mp3"
				}),
				win=love.audio.newSource({
					"npcs/goblin/goblin-laugh.mp3"
				})
			}
		}
