npc_types['rooster'] = {
			name="Rooster",
			color={148,198,180},
			hostile=false,
			move='random',
			vocal=true,
                        armour={
                                        {
                                                type="flesh",
                                                natural=true,
                                                value=1
                                        }
                        },
                        weapons={
                                        {
                                                name='beak',
                                                natural=true,
                                                attacks={
                                                        {
                                                                verbs={'pecks','pokes','scrapes','nips'},
                                                                damage={dice_qty=1,dice_sides=1,plus=1},
                                                                critical_chance_multiplier=0.2
                                                        }
                                                }
                                        }
                        },
			sounds={
				attack=love.audio.newSource({
					"npcs/rooster/rooster-call-1.mp3",
					"npcs/rooster/rooster-call-2.mp3",
					"npcs/rooster/rooster-call-3.mp3",
					"npcs/rooster/rooster-call-4.mp3",
					"npcs/rooster/rooster-call-5.mp3",
					"npcs/rooster/rooster-call-6.mp3",
					"npcs/rooster/rooster-call-7.mp3",
					"npcs/rooster/rooster-cluck-1.mp3",
					"npcs/rooster/rooster-cluck-10.mp3",
					"npcs/rooster/rooster-cluck-11.mp3",
					"npcs/rooster/rooster-cluck-2.mp3",
					"npcs/rooster/rooster-cluck-3.mp3",
					"npcs/rooster/rooster-cluck-4.mp3",
					"npcs/rooster/rooster-cluck-5.mp3",
					"npcs/rooster/rooster-cluck-6.mp3",
					"npcs/rooster/rooster-cluck-7.mp3",
					"npcs/rooster/rooster-cluck-8.mp3",
					"npcs/rooster/rooster-cluck-9.mp3",
					"npcs/rooster/rooster-crow-1.mp3",
					"npcs/rooster/rooster-crow-10.mp3",
					"npcs/rooster/rooster-crow-11.mp3",
					"npcs/rooster/rooster-crow-12.mp3",
					"npcs/rooster/rooster-crow-13.mp3",
					"npcs/rooster/rooster-crow-14.mp3",
					"npcs/rooster/rooster-crow-15.mp3",
					"npcs/rooster/rooster-crow-16.mp3",
					"npcs/rooster/rooster-crow-17.mp3",
					"npcs/rooster/rooster-crow-18.mp3",
					"npcs/rooster/rooster-crow-19.mp3",
					"npcs/rooster/rooster-crow-2.mp3",
					"npcs/rooster/rooster-crow-20.mp3",
					"npcs/rooster/rooster-crow-21.mp3",
					"npcs/rooster/rooster-crow-22.mp3",
					"npcs/rooster/rooster-crow-23.mp3",
					"npcs/rooster/rooster-crow-3.mp3",
					"npcs/rooster/rooster-crow-4.mp3",
					"npcs/rooster/rooster-crow-5.mp3",
					"npcs/rooster/rooster-crow-6.mp3",
					"npcs/rooster/rooster-crow-7.mp3",
					"npcs/rooster/rooster-crow-8.mp3",
					"npcs/rooster/rooster-crow-9.mp3"
				})
			}
		}
